Repository GwaChaePah/backend, pull requests merged in 2021-11, with the labels that each got.

#46 Feat: install drf & init setting
  gwachaepah_practice/settings.py
  requirements.txt
Labels: enhancement

#48 Feat: add meta data in serializer
  board/serializers.py
Labels: enhancement

#49 Feat: add ProductList class using generic
  board/views.py
Labels: enhancement

#50 Feat: add product-api url
  gwachaepah_practice/urls.py
Labels: enhancement

#52 Fix: product api list filtering
  board/views.py
Labels: fix

#54 Feat: add scheduler for delete old data & delete unused import
  board/management/commands/del_old_data.py
  board/management/commands/put_new_data.py
  board/open_api.py
Labels: enhancement

#55 Feat: add post-api
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement

#56 Feat: add comment-api
  board/migrations/0015_alter_comment_post_key.py
  board/models.py
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement, help wanted, question, migration

#57 Fix: comments in board page are working
  templates/board.html
Labels: fix

#58 Feat: add search api
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement

#61 Modify: modify post_api to board_api
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: modify

#62 Feat: get comment data dynamically
  board/views.py
Labels: enhancement, modify

#63 Feat: merge post and comment in post-api
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement

#64 Feat: setting swagger
  gwachaepah_practice/settings.py
  gwachaepah_practice/urls.py
  requirements.txt
Labels: enhancement

#65 Modify: search api in url
  board/views.py
  gwachaepah_practice/urls.py
Labels: fix, modify

#66 Feat: create post
  board/forms.py
  board/views.py
  gwachaepah_practice/urls.py
  templates/board.html
  templates/new.html
Labels: enhancement

#68 Feat: add update and delete post
  board/views.py
  gwachaepah_practice/urls.py
  templates/board.html
  templates/edit.html
Labels: enhancement

#69 Feat: add post detail page
  board/views.py
  gwachaepah_practice/urls.py
  templates/board.html
  templates/show.html
Labels: enhancement

#70 HOTFIX: create comment not solved
  board/forms.py
  board/views.py
  gwachaepah_practice/urls.py
  templates/show.html
Labels: bug, help wanted

#71 Fix: comment create error
  board/forms.py
  board/views.py
  templates/show.html
Labels: fix

#72 Feat: update and delete comment
  board/views.py
  gwachaepah_practice/urls.py
  templates/show.html
Labels: enhancement

#74 Modify: api page size change
  gwachaepah_practice/settings.py
Labels: modify

#75 Modify: change post model time field to prev version
  board/migrations/0016_auto_20211107_1435.py
  board/models.py
Labels: modify

#76 Modify: upload path in post model
  board/migrations/0017_alter_post_image1.py
  board/migrations/0018_alter_post_image1.py
  board/migrations/0019_auto_20211107_1550.py
  board/models.py
Labels: migration, modify

#78 Modify: api setting
  board/serializers.py
  board/views.py
Labels: modify

#79 Fix: show search param in swagger using querystring
  board/views.py
  gwachaepah_practice/urls.py
Labels: fix, modify

#80 Feat: add board data in search-api
  board/views.py
Labels: enhancement

#81 Bug: user login & logout
  board/forms.py
  board/views.py
  gwachaepah_practice/urls.py
  templates/board.html
  templates/main.html
Labels: bug, help wanted

#82 Modify: board-api filtering & revert search-api
  board/views.py
  gwachaepah_practice/urls.py
Labels: fix, modify

#87 Modify: search-api filtering & ordering & html img size
  board/views.py
  templates/board.html
  templates/show.html
Labels: modify

#88 Feat: take access, refresh token using jwt
  board/views.py
  gwachaepah_practice/settings.py
  gwachaepah_practice/urls.py
  requirements.txt
Labels: enhancement

#89 Modify: user setting
  board/admin.py
  board/forms.py
  board/migrations/0020_auto_20211109_1635.py
  board/models.py
Labels: modify

#90 Modify: request user in post & comments
  board/forms.py
  board/views.py
Labels: enhancement

#92 Bug: add Post & PUT & Delete method in post
  board/views.py
Labels: bug, help wanted

#93 Bug: cannot POST or PUT in Swagger & image POST error
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: bug, help wanted, question

#94 Delete: DateTimeField in serializer
  board/serializers.py
Labels: question, fix

#97 Feat: profile_table
  board/admin.py
  board/migrations/0002_profile.py
  board/models.py
Labels: enhancement, question

#99 Feat: add user register automatically add profile data
  board/forms.py
  board/models.py
  board/views.py
  gwachaepah_practice/urls.py
  templates/main.html
  templates/user_register.html
Labels: enhancement

#100 Modify: set Profile user_key to pk
  board/admin.py
  board/migrations/0003_auto_20211111_2050.py
  board/migrations/0004_auto_20211111_2053.py
  board/migrations/0005_auto_20211111_2120.py
  board/models.py
Labels: enhancement

#101 Feat: add CORS
  gwachaepah_practice/settings.py
Labels: enhancement, question

#102 Feat: for front random user can create post
  board/views.py
Labels: enhancement

#103 Ylee random user create post and comment
  board/views.py
Labels: fix

#104 Modify: devide board-api by role
  board/models.py
  board/views.py
  gwachaepah_practice/settings.py
  gwachaepah_practice/urls.py
Labels: modify

#105 Modify: PostList to show image field
  board/views.py
  gwachaepah_practice/urls.py
Labels: help wanted, question, fix

#106 Modify: test CORS setting
  gwachaepah_practice/settings.py
  requirements.txt
Labels: modify

#107 Modify: resetting update func in post-api & comment-api
  board/views.py
Labels: modify

#108 Modify: add MultiPartParser into CommentDetailList & PostList
  board/views.py
Labels: fix, modify

#111 Modify: ordering post in board
  board/views.py
Labels: modify

#112 Feat: user check for register
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement

#113 Fix: delete update function in PUT
  board/views.py
Labels: fix

#114 Feat: add read_only_fields in serializer
  board/serializers.py
Labels: enhancement

#116 Feat: add user api GET
  board/serializers.py
  board/views.py
  gwachaepah_practice/settings.py
  gwachaepah_practice/urls.py
Labels: enhancement

#117 Fix: divide serializer for POST
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: fix

#118 Modify: response user info with tokens when user try login
  board/serializers.py
Labels: fix, modify

#119 Modify: divide comment list and detail
  board/views.py
  gwachaepah_practice/urls.py
Labels: modify

#121 Change: api urls
  gwachaepah_practice/urls.py
Labels: style

#122 Modify: board search case exclude tag=2, include pagination
  board/views.py
Labels: modify

#123 Change: class name in views & organize import
  board/views.py
  gwachaepah_practice/urls.py
Labels: style

#124 Fix: import serializers from .
  board/views.py
Labels: bug

#125 Modify: rename profile field local to region
  board/admin.py
  board/migrations/0007_rename_local_profile_region.py
  board/models.py
  board/serializers.py
  board/views.py
Labels: style

#126 Feat: user register api
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
  templates/board.html
Labels: enhancement

#127 Modify: add comment cnt and username data when post get request
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement, modify

#128 Feat: add object level permissions
  board/permissions.py
  board/views.py
  gwachaepah_practice/settings.py
Labels: enhancement

#129 Feat: add username in comment
  board/serializers.py
Labels: modify

#130 Fix: return ImageField in Post model
  board/models.py
Labels: fix, modify

#131 Fix: view_count
  board/views.py
Labels: fix

#132 Modify: add more filter condition in search price list
  board/views.py
Labels: modify

#133 Fix: Search api Error fix
  board/views.py
Labels: fix

#134 Modify: add set_profile and remove signal in models
  board/models.py
  board/views.py
Labels: modify

#135 Modify: CORS settings
  gwachaepah_practice/settings.py
Labels: modify

#136 Feat: add api authentication setting
  board/views.py
  gwachaepah_practice/settings.py
  gwachaepah_practice/urls.py
Labels: enhancement

#137 Modify: add allow request url
  board/views.py
Labels: modify

#138 Modify: set custom permission classes in several cases
  board/views.py
Labels: modify

#139 Feat: django login/out in swagger
  gwachaepah_practice/settings.py
Labels: enhancement, fix, modify

#140 Modify: put get_permissions in all apis
  board/views.py
Labels: modify

#141 Delete: unused functions and files
  board/forms.py
  board/models.py
  board/open_api.py
  board/views.py
  gwachaepah_practice/settings.py
  gwachaepah_practice/urls.py
  templates/base.html
  templates/board.html
  templates/edit.html
  templates/main.html
  templates/new.html
  templates/search.html
  templates/show.html
  templates/user_register.html
Labels: style, delete

#142 Feat: region code csv file to database
  board/admin.py
  board/management/commands/db_uploader.py
  board/migrations/0008_auto_20211121_1400.py
  board/models.py
  gwachaepah_practice/urls.py
Labels: enhancement, migration, style, add database, modify

#143 Feat: add region api
  board/serializers.py
  board/views.py
  gwachaepah_practice/urls.py
Labels: enhancement

#144 Feat: filter region in board api
  board/serializers.py
  board/views.py
Labels: enhancement

#145 Feat: add region in post api
  board/serializers.py
Labels: enhancement
