Repository GwaChaePah/backend, pull requests merged in 2021-10, with the labels that each got.

#2 Feat: add product table
  .idea/gwachaepah_practice.iml
  .idea/misc.xml
  board/models.py
Labels: enhancement

#6 Feat: add Class Product in models.py
  board/admin.py
Labels: enhancement

#8 Fix: edit small bugs migrate error
  .gitignore
  board/__pycache__/__init__.cpython-38.pyc
  board/__pycache__/admin.cpython-38.pyc
  board/__pycache__/apps.cpython-38.pyc
  board/__pycache__/models.cpython-38.pyc
  board/__pycache__/views.cpython-38.pyc
  board/migrations/0001_initial.py
  board/migrations/__pycache__/0001_initial.cpython-38.pyc
  board/migrations/__pycache__/__init__.cpython-38.pyc
  gwachaepah_practice/__pycache__/__init__.cpython-38.pyc
  gwachaepah_practice/__pycache__/settings.cpython-38.pyc
  gwachaepah_practice/__pycache__/urls.cpython-38.pyc
Labels: bug, enhancement

#14 Feat: add images to post_table
  .gitignore
  media/posts/img/corn.jpeg
  media/posts/img/peach.jpeg
  media/posts/img/potatoes.jpeg
Labels: documentation, enhancement, question

#17 Style: add / at 'images'
  board/migrations/0003_auto_20211014_1828.py
  board/models.py
  media/posts/img/potato.jpeg
  media/posts/img/potatoes.jpeg
  media/posts/img/potatto.jpeg
Labels: migration

#18 Feat: Random Product in Mainpage
  board/views.py
  templates/main.html
Labels: enhancement

#23 Fix: hide cloudinary secret info in settings.py by use heroku config var
  gwachaepah_practice/settings.py
Labels: duplicate

#28 Feat: add openapi all data
  board/__pycache__/__init__.cpython-38.pyc
  board/__pycache__/admin.cpython-38.pyc
  board/__pycache__/apps.cpython-38.pyc
  board/__pycache__/models.cpython-38.pyc
  board/__pycache__/views.cpython-38.pyc
  board/migrations/__pycache__/0001_initial.cpython-38.pyc
  board/migrations/__pycache__/0002_comment.cpython-38.pyc
  board/migrations/__pycache__/__init__.cpython-38.pyc
  board/open_api.py
  board/views.py
  gwachaepah_practice/__pycache__/__init__.cpython-38.pyc
  gwachaepah_practice/__pycache__/settings.cpython-38.pyc
  gwachaepah_practice/__pycache__/urls.cpython-38.pyc
  gwachaepah_practice/__pycache__/wsgi.cpython-38.pyc
  templates/search.html
Labels: enhancement
